databases:
  - name: med-mingle-db
    databaseName: medmingle
    user: medmingle_user
    plan: free

services:
  - type: web
    name: med-mingle
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: med-mingle-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: AI_MODERATION_URL
        value: https://ai-moderation-service.onrender.com 