#!/bin/bash

echo "🆓 Setting up FREE Supabase Database for Med Mingle"
echo "=================================================="
echo ""

echo "📋 Step-by-Step Instructions:"
echo "============================="
echo ""
echo "1. 🌐 Go to https://supabase.com"
echo "2. 🔑 Sign up/Login with GitHub"
echo "3. ➕ Click 'New Project'"
echo "4. 📝 Fill in details:"
echo "   - Organization: Create new or use existing"
echo "   - Name: med-mingle"
echo "   - Database Password: (create a strong password)"
echo "   - Region: Choose closest to you"
echo "5. ⏳ Wait 2-3 minutes for setup"
echo "6. 🔗 Get connection string:"
echo "   - Go to Settings → Database"
echo "   - Copy 'Connection string' (URI format)"
echo ""
echo "🔗 Your connection string will look like:"
echo "postgresql://postgres:[YOUR-PASSWORD]@db.[PROJECT-REF].supabase.co:5432/postgres"
echo ""

echo "⚡ Quick Commands (run after getting connection string):"
echo "======================================================="
echo ""
echo "# Add your database URL (replace with your actual string):"
echo "vercel env add DATABASE_URL production"
echo ""
echo "# Add OpenAI API key (get from https://platform.openai.com):"
echo "vercel env add OPENAI_API_KEY production"
echo ""
echo "# Deploy to production:"
echo "vercel --prod"
echo ""

echo "🎯 Benefits of Supabase:"
echo "========================"
echo "✅ Completely FREE"
echo "✅ 500MB database"
echo "✅ 50,000 monthly active users"
echo "✅ Real-time subscriptions"
echo "✅ Built-in authentication"
echo "✅ Auto-generated APIs"
echo "✅ PostgreSQL compatible"
echo ""

echo "🚀 Ready to start? Go to https://supabase.com now!"
echo ""
echo "💡 Need help? The setup takes about 5 minutes total." 